### ISSUE TITLE
Lazy load iframes

### ISSUE THREAD

**Issue by rayshan** [sto3psl/react-datawrapper-chart#3]
Hi! Thanks for this convenient library! Would you consider doing this? It saves data, speeds up the loading of other parts of the page, and reduces memory usage.

Reference: https://web.dev/iframe-lazy-loading/

**Comment by sto3psl** [comment]
Hey @rayshan!

You can actually already do that like this:

```js
<DWChart title="Chart" src="//datawrapper.dwcdn.net/rjRUb/7/" loading="lazy" />
```

`props` are passed to the underlying `<iframe />` with the exception of `title`, `src` and `height`.

**Comment by sto3psl** [comment]
I added some documentation to the [Readme](https://github.com/sto3psl/react-datawrapper-chart#props) about the `loading` attribute.

**Comment by rayshan** [comment]
Thank you!
